import type { Metadata } from "next";
import Providers from "@/components/Providers";
import { CssBaseline } from "@mui/material";
import { Player } from "@/components/Player";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <CssBaseline />
      <html lang="en">
        <body>
          <div style={{ position: "fixed", zIndex: 100, top: 16, left:"auto", right: 16, }}>
            <Player />
          </div>
          {children}
        </body>
      </html>
    </Providers>
  );
}
